management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: spring-blog
    description: A blog with articles about The Spring Framework.
    author: Buddhi Malinda
    version: '@1.0.0'
spring:
  profiles:
    active: dev